<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductoAcabadoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('producto_acabados')->delete();

        \DB::table('producto_acabados')->insert([
            ['sigla'=>'AVY_3026','nombre'=>'AVERY MPI3026'],
            ['sigla'=>'NOV_6030','nombre'=>'NOVA PRISMA 6030'],
            ['sigla'=>'NOV_40001','nombre'=>'NOVA PRISMA ALTA GAMA 40001 '],
            ['sigla'=>'NOV_40003','nombre'=>'NOVA PRISMA ALTA ADH 40003'],
            ['sigla'=>'GLR_50001','nombre'=>'GLASS RITRAMA 50001'],
            ['sigla'=>'GLR_50400','nombre'=>'GLASS RITRAMA 50400'],
            ['sigla'=>'MTL_979860','nombre'=>'MAC TAC 979860 LIGHT DIFUSER'],
            ['sigla'=>'MTW_982800','nombre'=>'MAC TAC 982800 MATT WHITE'],
            ['sigla'=>'MTB_988800','nombre'=>'MAC TAC 988800 MATT BLACK'],
            ['sigla'=>'ORO_6510038','nombre'=>'ORACAL RED ORANGE FLUORESCENTE'],
            ['sigla'=>'ORR_6510046','nombre'=>'ORACAL ROSA FLUORESCENTE'],
            ['sigla'=>'MAG_AGF','nombre'=>'MAGENTA AGFA'],
            ['sigla'=>'2C','nombre'=>'2CARAS'],
            ['sigla'=>'AVY_501EF','nombre'=>'AVERY MATT WHITE 501EF'],
            ['sigla'=>'AVY_502EF','nombre'=>'AVERY MATT BLACK 502EF'],
            ['sigla'=>'AVY_503EF','nombre'=>'AVERY 503EF MATT GERANIUM RED '],
            ['sigla'=>'AVY_504EF','nombre'=>'AVERY PIMROSE YELLOW 504EF'],
            ['sigla'=>'AVY_507EF','nombre'=>'AVERY MATT BROWN 507EF'],
            ['sigla'=>'AVY_519EF','nombre'=>'AVERY MATT RED 519EF'],
            ['sigla'=>'AVY_524EF','nombre'=>'AVERY MATT MAGENTA 524EF'],
            ['sigla'=>'BOS_89701E','nombre'=>'BRITE OVEREALL SILVER DURABLE'],
            ['sigla'=>'AGF','nombre'=>'AGFA'],
            ['sigla'=>'ADH','nombre'=>'ADHESIVA'],
            ['sigla'=>'ANT','nombre'=>'ANTIDESLIZANTE'],
            ['sigla'=>'BOL','nombre'=>'BOLSA 1KG'],
            ['sigla'=>'K_AGF','nombre'=>'BLACK AGFA'],
            ['sigla'=>'BACK','nombre'=>'BACKLITE'],
            ['sigla'=>'BC','nombre'=>'BLACK CANON'],
            ['sigla'=>'BD','nombre'=>'BLACK DURST'],
            ['sigla'=>'BLACK','nombre'=>'NEGRO'],
            ['sigla'=>'BO','nombre'=>'BORDELESS  OFIJET'],
            ['sigla'=>'BR','nombre'=>'BRILLO'],
            ['sigla'=>'CAN','nombre'=>'CANON'],
            ['sigla'=>'CHO','nombre'=>'CHOPO'],
            ['sigla'=>'COL','nombre'=>'COLOR'],
            ['sigla'=>'CUE','nombre'=>'CUERO'],
            ['sigla'=>'CYA_agf','nombre'=>'CYAN AGFA'],
            ['sigla'=>'CYA_CAN','nombre'=>'CYAN CANON'],
            ['sigla'=>'CYA_DUR','nombre'=>'CYAN DURST'],
            ['sigla'=>'CYA_OFI','nombre'=>'CYAN OFIJET'],
            ['sigla'=>'COM','nombre'=>'en blanco)'],
            ['sigla'=>'CEP','nombre'=>'CEPILLADO'],
            ['sigla'=>'CRE','nombre'=>'CREPE'],
            ['sigla'=>'CRU','nombre'=>'CRUDO'],
            ['sigla'=>'CAS','nombre'=>'CANALSIMPLE'],
            ['sigla'=>'DUR','nombre'=>'DURST'],
            ['sigla'=>'DRY_DAWBL995','nombre'=>'DRY APPLY WBL995'],
            ['sigla'=>'DCA_3MFM1750','nombre'=>'3MFM1750 DOBLE CARA'],
            ['sigla'=>'DCA','nombre'=>'DOBLE CARA'],
            ['sigla'=>'DUG','nombre'=>'DUGOPA'],
            ['sigla'=>'E2C_MAT','nombre'=>'ESTUCADO 2 CARAS MATE'],
            ['sigla'=>'EIN','nombre'=>'EXTRUSION INCOLORO'],
            ['sigla'=>'ERA_230120W','nombre'=>'TOTAL ERAZE 23012C BLANCO'],
            ['sigla'=>'EWO','nombre'=>'EXTRUSION BLANCO OPACO'],
            ['sigla'=>'EWOP','nombre'=>'EXTRUSION BLANCO OPAL'],
            ['sigla'=>'FBR','nombre'=>'FUJI BRILLO'],
            ['sigla'=>'FMT','nombre'=>'FUJI MATE'],
            ['sigla'=>'GEN','nombre'=>'GENESIS'],
            ['sigla'=>'GO','nombre'=>'GREEN OFIJET'],
            ['sigla'=>'IN','nombre'=>'INCOLORO'],
            ['sigla'=>'KFT','nombre'=>'KRAFT'],
            ['sigla'=>'KNV','nombre'=>'KRAFT NATURAL VERJURADO 90'],
            ['sigla'=>'KVH','nombre'=>'VERJURADO HOLANDES'],
            ['sigla'=>'KVR','nombre'=>'VERJURADO RADIOGRAFIA'],
            ['sigla'=>'LCA','nombre'=>'LIGHT CYAN AGFA'],
            ['sigla'=>'LCO','nombre'=>'LIGHT CYAN OFIJET'],
            ['sigla'=>'LKO','nombre'=>'LIGHT BACK OFIJET'],
            ['sigla'=>'LMA','nombre'=>'LIGHT MAGENTA AGFA'],
            ['sigla'=>'LMO','nombre'=>'LIGHT MAGENTA OFIJET'],
            ['sigla'=>'MBR','nombre'=>'MONOMERICO BRILLO'],
            ['sigla'=>'MC','nombre'=>'MAGENTA CANON'],
            ['sigla'=>'MD','nombre'=>'MAGENTA DURST'],
            ['sigla'=>'MKO','nombre'=>'MATTE BACK OFIJET'],
            ['sigla'=>'MMT','nombre'=>'MONOMERICO MATE'],
            ['sigla'=>'MS55','nombre'=>'MS55'],
            ['sigla'=>'MT','nombre'=>'MATE'],
            ['sigla'=>'N','nombre'=>'NORMAL'],
            ['sigla'=>'O','nombre'=>'OFIJET'],
            ['sigla'=>'OO','nombre'=>'ORANGE OFIJET'],
            ['sigla'=>'ORO','nombre'=>'ORO'],
            ['sigla'=>'OW','nombre'=>'OFFSET BLANCO'],
            ['sigla'=>'PA','nombre'=>'PRIMER AGFA'],
            ['sigla'=>'PBR','nombre'=>'POLIMERICO BRILLO'],
            ['sigla'=>'PGH','nombre'=>'PAPER GRAPHICS'],
            ['sigla'=>'PKO','nombre'=>'PHOTO BACK OFIJET'],
            ['sigla'=>'PLATA','nombre'=>'PLATA'],
            ['sigla'=>'PPP','nombre'=>'PRECINTO POLIPROPILENO TRANSP'],
            ['sigla'=>'PSU','nombre'=>'POLIMERICO SATIN UVA'],
            ['sigla'=>'PTEX','nombre'=>'PLATA EXTERIOR'],
            ['sigla'=>'PTIN','nombre'=>'PLATA INTERIOR'],
            ['sigla'=>'PW','nombre'=>'POLITENO BLANCO'],
            ['sigla'=>'RED','nombre'=>'ROJO'],
            ['sigla'=>'SAC','nombre'=>'SACO'],
            ['sigla'=>'SFR','nombre'=>'SOLATUV FR'],
            ['sigla'=>'SLK','nombre'=>'SILK'],
            ['sigla'=>'STD','nombre'=>'STANDARD'],
            ['sigla'=>'TMTBR','nombre'=>'TRANSPARENTE MATE BRILLO'],
            ['sigla'=>'TMTMT','nombre'=>'TRANSPARENTE MATE MATE'],
            ['sigla'=>'TR','nombre'=>'TRANSPARENTE'],
            ['sigla'=>'TW','nombre'=>'TRASERA BLANCA'],
            ['sigla'=>'UC','nombre'=>'ULTRA CRISTALINO'],
            ['sigla'=>'UNI','nombre'=>'UNIVERSAL'],
            ['sigla'=>'UW','nombre'=>'UNIVERSAL BLANCO'],
            ['sigla'=>'VAN','nombre'=>'VILEDA ANTIGRAFFITI'],
            ['sigla'=>'VBR','nombre'=>'VELLEDA CB90 BRILLO'],
            ['sigla'=>'VMO','nombre'=>'VIVID MAGENTA OFIJET'],
            ['sigla'=>'VMT','nombre'=>'VELLEDA CB75 MATE'],
            ['sigla'=>'VO','nombre'=>'VIOLET OFIJET'],
            ['sigla'=>'VPO','nombre'=>'PARA OPACAR'],
            ['sigla'=>'W','nombre'=>'BLANCO'],
            ['sigla'=>'WA','nombre'=>'WHITE AGFA'],
            ['sigla'=>'WBR','nombre'=>'BLANCO BRILLO'],
            ['sigla'=>'WBRH','nombre'=>'BLANCO BRILLO HOP'],
            ['sigla'=>'WC','nombre'=>'WHITE CANON'],
            ['sigla'=>'WE','nombre'=>'BLANCO ESTUCADO'],
            ['sigla'=>'WE2C','nombre'=>'BLANCO ESTUCADO 2 CARAS'],
            ['sigla'=>'WFW','nombre'=>'BLANCO KRAFT BLANCO'],
            ['sigla'=>'WKW','nombre'=>'BLANCO NEGRO BLANCO'],
            ['sigla'=>'WMT','nombre'=>'BLANCO MATE'],
            ['sigla'=>'WMTADH','nombre'=>'BLANCO MATE ADHESIVO'],
            ['sigla'=>'WMTH','nombre'=>'BLANCO MATE HOP'],
            ['sigla'=>'WOP','nombre'=>'BLANCO OPAL'],
            ['sigla'=>'WPT','nombre'=>'WALL PRINT  IJ480'],
            ['sigla'=>'WTRAS','nombre'=>'BLANCO TRASLUCIDO'],
            ['sigla'=>'WWW','nombre'=>'BLANCO BLANCO BLANCO'],
            ['sigla'=>'YA','nombre'=>'YELLOW AGFA'],
            ['sigla'=>'YC','nombre'=>'YELLOW CANON'],
            ['sigla'=>'YD','nombre'=>'YELLOW DURST'],
            ['sigla'=>'YO','nombre'=>'YELLOW OFIJET'],
            ['sigla'=>'Z','nombre'=>'KATZ'],
        ]);
    }
}
