<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductoAcabadoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('producto_acabados')->delete();

        \DB::table('producto_acabados')->insert([
            ['id'=>'AVY_3026','nombre'=>'AVERY MPI3026'],
            ['id'=>'NOV_6030','nombre'=>'NOVA PRISMA 6030'],
            ['id'=>'NOV_40001','nombre'=>'NOVA PRISMA ALTA GAMA 40001 '],
            ['id'=>'NOV_40003','nombre'=>'NOVA PRISMA ALTA ADH 40003'],
            ['id'=>'GLR_50001','nombre'=>'GLASS RITRAMA 50001'],
            ['id'=>'GLR_50400','nombre'=>'GLASS RITRAMA 50400'],
            ['id'=>'MTL_979860','nombre'=>'MAC TAC 979860 LIGHT DIFUSER'],
            ['id'=>'MTW_982800','nombre'=>'MAC TAC 982800 MATT WHITE'],
            ['id'=>'MTB_988800','nombre'=>'MAC TAC 988800 MATT BLACK'],
            ['id'=>'ORO_6510038','nombre'=>'ORACAL RED ORANGE FLUORESCENTE'],
            ['id'=>'ORR_6510046','nombre'=>'ORACAL ROSA FLUORESCENTE'],
            ['id'=>'MAG_AGF','nombre'=>'MAGENTA AGFA'],
            ['id'=>'2C','nombre'=>'2CARAS'],
            ['id'=>'AVY_501EF','nombre'=>'AVERY MATT WHITE 501EF'],
            ['id'=>'AVY_502EF','nombre'=>'AVERY MATT BLACK 502EF'],
            ['id'=>'AVY_503EF','nombre'=>'AVERY 503EF MATT GERANIUM RED '],
            ['id'=>'AVY_504EF','nombre'=>'AVERY PIMROSE YELLOW 504EF'],
            ['id'=>'AVY_507EF','nombre'=>'AVERY MATT BROWN 507EF'],
            ['id'=>'AVY_519EF','nombre'=>'AVERY MATT RED 519EF'],
            ['id'=>'AVY_524EF','nombre'=>'AVERY MATT MAGENTA 524EF'],
            ['id'=>'BOS_89701E','nombre'=>'BRITE OVEREALL SILVER DURABLE'],
            ['id'=>'AGF','nombre'=>'AGFA'],
            ['id'=>'ADH','nombre'=>'ADHESIVA'],
            ['id'=>'ANT','nombre'=>'ANTIDESLIZANTE'],
            ['id'=>'BOL','nombre'=>'BOLSA 1KG'],
            ['id'=>'K_AGF','nombre'=>'BLACK AGFA'],
            ['id'=>'BACK','nombre'=>'BACKLITE'],
            ['id'=>'BC','nombre'=>'BLACK CANON'],
            ['id'=>'BD','nombre'=>'BLACK DURST'],
            ['id'=>'BLACK','nombre'=>'NEGRO'],
            ['id'=>'BO','nombre'=>'BORDELESS  OFIJET'],
            ['id'=>'BR','nombre'=>'BRILLO'],
            ['id'=>'CAN','nombre'=>'CANON'],
            ['id'=>'CHO','nombre'=>'CHOPO'],
            ['id'=>'COL','nombre'=>'COLOR'],
            ['id'=>'CUE','nombre'=>'CUERO'],
            ['id'=>'CYA_agf','nombre'=>'CYAN AGFA'],
            ['id'=>'CYA_CAN','nombre'=>'CYAN CANON'],
            ['id'=>'CYA_DUR','nombre'=>'CYAN DURST'],
            ['id'=>'CYA_OFI','nombre'=>'CYAN OFIJET'],
            ['id'=>'COM','nombre'=>'en blanco)'],
            ['id'=>'CEP','nombre'=>'CEPILLADO'],
            ['id'=>'CRE','nombre'=>'CREPE'],
            ['id'=>'CRU','nombre'=>'CRUDO'],
            ['id'=>'CAS','nombre'=>'CANALSIMPLE'],
            ['id'=>'DUR','nombre'=>'DURST'],
            ['id'=>'DRY_DAWBL995','nombre'=>'DRY APPLY WBL995'],
            ['id'=>'DCA_3MFM1750','nombre'=>'3MFM1750 DOBLE CARA'],
            ['id'=>'DCA','nombre'=>'DOBLE CARA'],
            ['id'=>'DUG','nombre'=>'DUGOPA'],
            ['id'=>'E2C_MAT','nombre'=>'ESTUCADO 2 CARAS MATE'],
            ['id'=>'EIN','nombre'=>'EXTRUSION INCOLORO'],
            ['id'=>'ERA_230120W','nombre'=>'TOTAL ERAZE 23012C BLANCO'],
            ['id'=>'EWO','nombre'=>'EXTRUSION BLANCO OPACO'],
            ['id'=>'EWOP','nombre'=>'EXTRUSION BLANCO OPAL'],
            ['id'=>'FBR','nombre'=>'FUJI BRILLO'],
            ['id'=>'FMT','nombre'=>'FUJI MATE'],
            ['id'=>'GEN','nombre'=>'GENESIS'],
            ['id'=>'GO','nombre'=>'GREEN OFIJET'],
            ['id'=>'IN','nombre'=>'INCOLORO'],
            ['id'=>'KFT','nombre'=>'KRAFT'],
            ['id'=>'KNV','nombre'=>'KRAFT NATURAL VERJURADO 90'],
            ['id'=>'KVH','nombre'=>'VERJURADO HOLANDES'],
            ['id'=>'KVR','nombre'=>'VERJURADO RADIOGRAFIA'],
            ['id'=>'LCA','nombre'=>'LIGHT CYAN AGFA'],
            ['id'=>'LCO','nombre'=>'LIGHT CYAN OFIJET'],
            ['id'=>'LKO','nombre'=>'LIGHT BACK OFIJET'],
            ['id'=>'LMA','nombre'=>'LIGHT MAGENTA AGFA'],
            ['id'=>'LMO','nombre'=>'LIGHT MAGENTA OFIJET'],
            ['id'=>'MBR','nombre'=>'MONOMERICO BRILLO'],
            ['id'=>'MC','nombre'=>'MAGENTA CANON'],
            ['id'=>'MD','nombre'=>'MAGENTA DURST'],
            ['id'=>'MKO','nombre'=>'MATTE BACK OFIJET'],
            ['id'=>'MMT','nombre'=>'MONOMERICO MATE'],
            ['id'=>'MS55','nombre'=>'MS55'],
            ['id'=>'MT','nombre'=>'MATE'],
            ['id'=>'N','nombre'=>'NORMAL'],
            ['id'=>'O','nombre'=>'OFIJET'],
            ['id'=>'OO','nombre'=>'ORANGE OFIJET'],
            ['id'=>'ORO','nombre'=>'ORO'],
            ['id'=>'OW','nombre'=>'OFFSET BLANCO'],
            ['id'=>'PA','nombre'=>'PRIMER AGFA'],
            ['id'=>'PBR','nombre'=>'POLIMERICO BRILLO'],
            ['id'=>'PGH','nombre'=>'PAPER GRAPHICS'],
            ['id'=>'PKO','nombre'=>'PHOTO BACK OFIJET'],
            ['id'=>'PLATA','nombre'=>'PLATA'],
            ['id'=>'PPP','nombre'=>'PRECINTO POLIPROPILENO TRANSP'],
            ['id'=>'PSU','nombre'=>'POLIMERICO SATIN UVA'],
            ['id'=>'PTEX','nombre'=>'PLATA EXTERIOR'],
            ['id'=>'PTIN','nombre'=>'PLATA INTERIOR'],
            ['id'=>'PW','nombre'=>'POLITENO BLANCO'],
            ['id'=>'RED','nombre'=>'ROJO'],
            ['id'=>'SAC','nombre'=>'SACO'],
            ['id'=>'SFR','nombre'=>'SOLATUV FR'],
            ['id'=>'SLK','nombre'=>'SILK'],
            ['id'=>'STD','nombre'=>'STANDARD'],
            ['id'=>'TMTBR','nombre'=>'TRANSPARENTE MATE BRILLO'],
            ['id'=>'TMTMT','nombre'=>'TRANSPARENTE MATE MATE'],
            ['id'=>'TR','nombre'=>'TRANSPARENTE'],
            ['id'=>'TW','nombre'=>'TRASERA BLANCA'],
            ['id'=>'UC','nombre'=>'ULTRA CRISTALINO'],
            ['id'=>'UNI','nombre'=>'UNIVERSAL'],
            ['id'=>'UW','nombre'=>'UNIVERSAL BLANCO'],
            ['id'=>'VAN','nombre'=>'VILEDA ANTIGRAFFITI'],
            ['id'=>'VBR','nombre'=>'VELLEDA CB90 BRILLO'],
            ['id'=>'VMO','nombre'=>'VIVID MAGENTA OFIJET'],
            ['id'=>'VMT','nombre'=>'VELLEDA CB75 MATE'],
            ['id'=>'VO','nombre'=>'VIOLET OFIJET'],
            ['id'=>'VPO','nombre'=>'PARA OPACAR'],
            ['id'=>'W','nombre'=>'BLANCO'],
            ['id'=>'WA','nombre'=>'WHITE AGFA'],
            ['id'=>'WBR','nombre'=>'BLANCO BRILLO'],
            ['id'=>'WBRH','nombre'=>'BLANCO BRILLO HOP'],
            ['id'=>'WC','nombre'=>'WHITE CANON'],
            ['id'=>'WE','nombre'=>'BLANCO ESTUCADO'],
            ['id'=>'WE2C','nombre'=>'BLANCO ESTUCADO 2 CARAS'],
            ['id'=>'WFW','nombre'=>'BLANCO KRAFT BLANCO'],
            ['id'=>'WKW','nombre'=>'BLANCO NEGRO BLANCO'],
            ['id'=>'WMT','nombre'=>'BLANCO MATE'],
            ['id'=>'WMTADH','nombre'=>'BLANCO MATE ADHESIVO'],
            ['id'=>'WMTH','nombre'=>'BLANCO MATE HOP'],
            ['id'=>'WOP','nombre'=>'BLANCO OPAL'],
            ['id'=>'WPT','nombre'=>'WALL PRINT  IJ480'],
            ['id'=>'WTRAS','nombre'=>'BLANCO TRASLUCIDO'],
            ['id'=>'WWW','nombre'=>'BLANCO BLANCO BLANCO'],
            ['id'=>'YA','nombre'=>'YELLOW AGFA'],
            ['id'=>'YC','nombre'=>'YELLOW CANON'],
            ['id'=>'YD','nombre'=>'YELLOW DURST'],
            ['id'=>'YO','nombre'=>'YELLOW OFIJET'],
            ['id'=>'Z','nombre'=>'KATZ'],
        ]);
    }
}
